### ISSUE TITLE
Give some examples

### ISSUE THREAD

**Issue by r2qokk** [simo5/jwcrypto#14]
Is it possible to add some quick examples to demonstrate how to establish a JWT or JWS in the document?
It will be great to see JWS and JWE in action in the same time.

**Comment by simo5** [comment]
Can you give more specifics about what use case you'd want to document ?

I have some example code in projects that use jwcrypto plus the tests I can refernce.

**Comment by r2qokk** [comment]
The document of JWK says the following.

>The function arguments must be valid parameters as defined in the ‘IANA JSON Web Key Set Parameters registry’ and specified in the JWKParamsRegistry variable. The ‘kty’ parameter must always be provided ...
>
Alternatively if the ‘generate’ parameter is provided, with a valid key type as value then a new key will be generated according to the defaults or provided key streng[th] options (type specific).

Which one should I use? `kty` or `generate`?
I have no idea. Maybe that is caused by my English reading ability.
I tried `generate`, which sounds more intuitive, but still got stuck in making a token.

The document of `JWT` says that it has a method name `make_signed_token()`, and the description says:
>Creates a JWS token with the header as the JWS protected header and the claims as the payload. See (jwcrypto.jws.JWS) for details on the exceptions that may be reaised.

In this, I suppose that I don't need to create a `JWS` object, since this method take only one parameter which needs to be a `JWK` object, and this function will return a `JWS` object.
```python
>>> from jwcrypto import jwk, jwt
>>> key = jwk.JWK(generate="oct", size=8)
>>> key.export()
'{"k":"BA","kty":"oct"}'
>>> key.export_public()
'{"kty":"oct"}'

# trying for the right configuration
>>> token = jwt.JWT()
>>> token.make_signed_token(key)
# modified the exception
  File "\jwcrypto\jwt.py", line 61, in claims
    raise KeyError("'claims' not set")
KeyError: "'claims' not set"

>>> token = jwt.JWT(claims=dict(test=1))
>>> token.make_signed_token(key)
  File "\jwcrypto\jwt.py", line 48, in header
    raise KeyError("'header' not set")
KeyError: "'header' not set"

>>> token = jwt.JWT(claims=dict(test=1), header=dict(test=2))
>>> token.make_signed_token(key)
  File "\jwcrypto\jwt.py", line 93, in make_signed_token
    t.add_signature(key, protected=self.header)
  File "\jwcrypto\jws.py", line 536, in add_signature
    raise ValueError('"alg" not specified')
ValueError: "alg" not specified

>>> token = jwt.JWT(claims=dict(test=1), header=dict(test=2), algs="HS256")
>>> token.make_signed_token(key)
  File "\jwcrypto\jwt.py", line 93, in make_signed_token
    t.add_signature(key, protected=self.header)
  File "\jwcrypto\jws.py", line 536, in add_signature
    raise ValueError('"alg" not specified')
ValueError: "alg" not specified

>>> token = jwt.JWT(claims=dict(test=1), header=dict(test=2), alg="HS256")
TypeError: __init__() got an unexpected keyword argument 'alg'
```

Please give some examples on how to make a token, and make the token signed and/or encrypted.

**Comment by simo5** [comment]
How to make an encrypted token:
https://github.com/simo5/jwcrypto/blob/master/jwcrypto/tests.py#L729

Here I use JWT to make a signed token in the Custodia project:
https://github.com/simo5/custodia/blob/master/custodia/message/kem.py#L229
A signed + encrypted token is generated in the follwing function.

I will keep this issue open as a remainder to add an examples section in the documentation to ahave itr explained more organically.

**Comment by r2qokk** [comment]
Just run through this
https://github.com/simo5/custodia/blob/master/custodia/message/kem.py#L137
I still don't know how to prepare an asymmetry key, like RSA or EC, but I can generate a symmetry key now.

Here is a draft that you may put into the package document
```python
import time

from jwcrypto import jwk
from jwcrypto import jws
from jwcrypto import jwe
from jwcrypto import jwt
###
# need document on jwcrypto.common
###
from jwcrypto.common import json_encode
from jwcrypto.common import json_decode


#  generate symmetry key
key = jwk.JWK(generate="oct", size=512)
# see what is in the key
key.export()
#
#'{"k":"nURsMz_LDfXvFcQJ4gK-XYlI9lorlwVqMDs-hmFyf4u8SX7KKgjvJJEWD6TD1tKwUB3t2s5dSQ-27Yo-8hQ4Fw","kty":"oct"}'
#


# prepareing payload, and add in reserved claims here
claims = dict(exp=int(time.time() + (3 * 60)))
# specify algorithm needed for JWS
header = dict(alg="HS512")


# making a JWT with singnature = JWS
T = jwt.JWT(header, claims)
# add signature
T.make_signed_token(key)
# JWS token string
T.serialize(compact=True)
#
#u'eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE0NDg1MDgxODh9.ji2kzoXTtBmrDxuU2UfwYzZK0wX9PjLbuiD2XLeaWsUu1vSZYO0sCRKOePyh0sck4qU1ohzwGB2P0Q81A'
#
signed_token = T.serialize(compact=True)


# JWE parameter description
# reference:
#	http://connect2id.com/products/nimbus-jose-jwt
eprot = {'alg': "dir", 'enc': "A256CBC-HS512"}
# encryped a JWS to make JWS+JWE or a btye string to make JWE
# json_encode() turn dict in to str in a certain format
E = jwe.JWE(signed_token, json_encode(eprot))
# encrypt with a key
E.add_recipient(key)
# JWE token string
E.serialize(compact=True)
#
#u'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIn0..79xaSmtj-GjVqrXIMeQneA.DWqXCs-P1ozIhn9rS_WzRTvr1_YfAlP-tZEK8UEl0NJt-hfkaUCG-5LmTLk38DA-PChhCtJVNceupyfWzj_E61nMTWuSgKnSESOFykUk25aF9UhexUSehIO4TE05EpNibTIgh6n4fJgP5MAq8jnI4sh4MLLlGIqVlvewYbCXcMSQul4KnNFzkN.WYc5sdRGNrw_uZEtSIfPTyC7jda1hS2m8CQP1pRkR7w'
#
encrypted_signed_token = E.serialize(compact=True)



# unpack the token
# 1. make the token string into JWT object
# 2. decrypt, if the token is JWE or JWS+JWE
# 3. verify, if the token is JWS
# 4. take the payload


# unpack JWS token
# make string into JWT object
###
# need document on '.token'
###
testing_token = jwt.JWT(jwt=signed_token).token

# extract JWS token payload before verification will raise a `InvalidJWSOperation` error
#
#testing_token.payload
#
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "\jwcrypto\jws.py", line 631, in payload
#    raise InvalidJWSOperation("Payload not verified")
#jwcrypto.jws.InvalidJWSOperation: Payload not verified
#

# verify token
testing_token.verify(key)
# take payload
payload = testing_token.payload
#
#'{"exp":1448508188}'
#
# turn str into dictionary
json_decode(payload)
#
#{u'exp': 1448508188}
#


# unpack JWE token
testing_token = jwt.JWT(jwt=encrypted_signed_token).token

# extract JWE token payload before decryption will raise a `InvalidJWEOperation` error
#
#testing_token.payload
#
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "\jwcrypto\jwe.py", line 807, in payload
#    raise InvalidJWEOperation("Plaintext not available")
# jwcrypto.jwe.InvalidJWEOperation: Plaintext not available
#

# decrypt JWE token
testing_token.decrypt(key)
# the payload here is JWS string
raw_payload = testing_token.payload
#
#'eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE0NDg1MDgxODh9.ji2kzoXTtBmrDxuU2UfwYzZK0wX9PjLbuiD2XLeaWsUu1vSZYO0sCRKOePyh0sck4qUMohzwGB2P0Q81A'
#
# turn byte into string, and there is a JWS inside
payload = raw_payload.decode("utf-8")
#
#u'eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE0NDg1MDgxODh9.ji2kzoXTtBmrDxuU2UfwYzZK0wX9PjLbuiD2XLeaWsUu1vSZYO0sCRKOePyh0sck4qU1ohzwGB2P0Q81A'
#

# unpack the JWS string again
S = jws.JWS()
S.deserialize(payload)
S
#
#<jwcrypto.jws.JWS object at 0x00000000030DE908>
#
token = S.verify(key)
payload = token.payload
#
#'{"exp":1448508188}'
#
json_decode(payload)
#
#{u'exp': 1448508188}
#
```
Please feel free to correct any term.

Need document on `jwcrypto.common`, and `.token` attribute in `JWS` and `JWT` module.
Also need JWE parameter description like this list in the following link, to make things clear.
http://connect2id.com/products/nimbus-jose-jwt
